version: '3.8'
services:

  backend:
    image: cloudobs-main
    ports:
      - '5000:5000'
    volumes:
      - ./sa.json:/app/sa.json

  frontend:
    image: cloudobs-client-main
    ports:
      - '3003:3000'
    environment:
      - CLOUD_OBS_HOST=backend-main
      - CLOUD_OBS_PORT=5000
    depends_on:
      - backend
