version: '3.8'
services:

  backend:
    image: cloudobs-$ENVIRONMENT
    env_file:
      - ./.env
    ports:
      - '127.0.0.1:$BACKEND_PORT:5000'
    volumes:
      - ./sa.json:/app/sa.json

  frontend:
    image: cloudobs-client-$ENVIRONMENT
    ports:
      - '127.0.0.1:$FRONTEND_PORT:3000'
    environment:
      - CLOUD_OBS_HOST=backend-$ENVIRONMENT
      - CLOUD_OBS_PORT=$BACKEND_PORT
    depends_on:
      - backend
